services:
  web-app:
    image: e-commerce-web-app:beta
    container_name: tomcat-ecomm
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    volumes:
      - ./webapp:/usr/local/tomcat/webapps/ROOT
      - ./build/classes/com/eazydeals:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/com/eazydeals

  mysqldb:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eazydeals
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./eazydeals_maven.sql:/docker-entrypoint-initdb.d/eazydeals_maven.sql

networks:
  custom_network:
    driver: bridge

volumes:
  db_data:
